package com.acme.service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-15T17:32:14.573+01:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://acme.com/services/event", name = "Event_PortType")
@XmlSeeAlso({com.acme.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EventPortType {

    @WebMethod(action = "http://acme.com/services/event/process")
    public void process(
        @WebParam(partName = "event", mode = WebParam.Mode.INOUT, name = "event", targetNamespace = "http://acme.com/types/event")
        javax.xml.ws.Holder<com.acme.types.Event> event
    );
}
